### ISSUE TITLE
Upgrade buffalo to 0.14

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme_backend#11]
There is a new version of buffalo out https://blog.gobuffalo.io/buffalo-v0-14-0-released-75e9d71677be

**Comment by himankpathak** [comment]
Hi @alexdor, I would like to work on this. Can you assign me the issue?

**Comment by alexdor** [comment]
I can't assign it to you because it doesn't show you in the list of possible assignees but feel free to work on it, consider it yours

**Comment by alexdor** [comment]
closed by 5651795cfff028bcfc87628f08856f2d07f3b825
