### ISSUE TITLE
Finish up work started at #7

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme_backend#12]
#7 includes some core functionality that will allow us to improve sorting of issues. The pull request is almost done but it needs a few improvements that are listed inside the pull request

**Comment by himankpathak** [comment]
Hi alexdor, I am working on it.

**Comment by alexdor** [comment]
Sounds good :)

**Comment by hv7214** [comment]
@alexdor is this issue still unsolved? If yes, then i'm willing to take this up.

**Comment by alexdor** [comment]
This one should be resolved by @himankpathak 's pull request

Unfortunately @kounelisagis decided to merge some of his pull requests that broke the repo and created multiple problems. Until I can get access to revert the broken pull requests I can't merge any changes

**Comment by hv7214** [comment]
Okay i got it!

**Comment by alexdor** [comment]
@hv7214 Would you be interested in tackling #16 ?

**Comment by hv7214** [comment]
@alexdor yeah sure!😀

**Comment by alexdor** [comment]
@hv7214 it's yours then : ) Start your branch from the `fix-master` branch and not the master, because that one is the fixed version that is going to become the master.

Let me know if you need any help or if you face any issues : )
