### ISSUE TITLE
Add a caching layer

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme_backend#4]
Instead of fetching the issues from the database on every request a caching layer should be used (like Redis) in order to cache request responses until they are invalid

**Comment by Biboswan** [comment]
Hi I would like to work on this.

**Comment by alexdor** [comment]
Feel free to work on it @Biboswan : )

**Comment by alexdor** [comment]
@Biboswan what's the status of this one?

**Comment by Biboswan** [comment]
Yeah I will send a PR soon for review

**Comment by alexdor** [comment]
Closed by #18, e214a8d75fa86ae8194f570c1ce95cee5b835bf1, 22d4846489a803329c442b4575ccd02eb69db195, 5ce2b1d90b5233d1d2b0d8b3b5aab0fe0b38d29b
