### ISSUE TITLE
Fix issue sorting

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme_backend#5]
Each github issue has an updatedAt field. That field should be stored on a new database column. Once this is done the issue listing should sort the issues based on that column

**Comment by NemoMarx** [comment]
The UpdatedAt field already exists in schema.sql and issue.go. The only work that could be done here is sorting the issue listing, and I'm not sure if that belongs in the backend or the frontend. If the data is there the sorting doesn't sound complex though.

**Comment by alexdor** [comment]
@NemoMarx the existing updatedAt field shouldn't be changed. The purpose of the existing field is to keep track of when the database row is changed. A new column needs to be added (something like GithubUpdatedAt) to store the github updated at value

**Comment by NemoMarx** [comment]
Thanks for that clarification, that helps a lot!

**Comment by NemoMarx** [comment]
One more question, related to that.

In issue.go, the Issue struct lists
`UpdatedAt time.Time 'json:"updated_at" db:"updated_at"`
My reading of this is that it's pulling from the github apis JSON object for the updated at value, which seems to mean that it would be setting updatedAt based on what github has stored. Would it make more sense to point this at the new github_updated_at db entry instead, and then leave updatedAt for the time when the row in the db was updated?

**Comment by alexdor** [comment]
This `UpdatedAt time.Time 'json:"updated_at" db:"updated_at"` means that there will be a field in the model called UpdatedAt, with a type time.Time, when this field is rendered to json it would be called `updated_at` and when this field is passed to the database is should be called `updated_at`.

Each issue is populated with github info [here](https://github.com/ossn/fixme_backend/blob/master/worker/worker.go#L258)

**Comment by NemoMarx** [comment]
So worker.go is pulling from the github API, then?

**Comment by alexdor** [comment]
Yeah worker.go is the one consuming GitHub’s GraphQL api

**Comment by alexdor** [comment]
Do you have any familiarity with GraphQL? Is there something that I can
help with?

**Comment by NemoMarx** [comment]
I have never used GraphQL before, unfortunately. I was assuming it was similar to a normal REST API, where there's a set JSON structure that you're expecting and pulling data out of it, but it doesn't look like that?

**Comment by NemoMarx** [comment]
Wait! Nevermind, I finally found the right page in the GraphQL documentation, I think I have a tentative change that would add it to schema.sql, issue.go, and worker.go.
