### ISSUE TITLE
Improve worker logic

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme_backend#6]
Right now the worker runs every 5' . A more advanced logic should be implimented based on the remaining github api requests

**Comment by aswinmprabhu** [comment]
Hey @alexdor, Can you please provide more context on this issue so that I can work on it? By remaining api requests do you mean the [rate limits](https://developer.github.com/v4/guides/resource-limitations/)?

**Comment by alexdor** [comment]
Yes, you are right, I mean the rate limit : ) 

The idea is to get issues from the repos until we reach the rate limit, once the worker reaches the rate limit it should wait until the limit has been refreshed and continue from where it stopped.
